/**
 * POST /api/inspections/notify
 *
 * Emails a completed pre-trip inspection to the EHS inbox. Best-effort and
 * env-gated: if RESEND_API_KEY is unset this is a no-op (returns emailed:false)
 * so the inspection flow is never blocked. Mirrors the safety review email path.
 */

import { z } from 'zod'
import { requireSession } from '@/lib/api-auth'
import { rateLimit } from '@/lib/rate-limit'
import { sendEhsNotification, isEmailConfigured } from '@/lib/email-notify'

function fmt(iso: string): string {
  return new Date(iso).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

const InspectionItemSchema = z.object({
  id: z.string().max(100),
  label: z.string().max(200),
  result: z.enum(['pass', 'fail', 'na']),
  critical: z.boolean().optional(),
  notes: z.string().max(1000).optional(),
})

const NotifyBodySchema = z.object({
  record: z.object({
    id: z.string().max(100),
    equipmentId: z.string().max(100),
    inspectorName: z.string().max(200),
    shift: z.string().max(50),
    hourMeterReading: z.number().nullable().optional(),
    createdAt: z.string().max(50),
    result: z.enum(['pass', 'fail']),
    hasCriticalFail: z.boolean(),
    workOrderId: z.string().max(100).optional(),
    items: z.array(InspectionItemSchema).max(200),
  }),
  equipmentName: z.string().max(200).optional(),
  equipmentCategory: z.string().max(200).optional(),
})

type NotifyBody = z.infer<typeof NotifyBodySchema>

function buildInspectionEmail(b: NotifyBody): { subject: string; text: string } {
  const r = b.record
  const equip = b.equipmentName || `Equipment #${r.equipmentId}`
  const verdict = r.hasCriticalFail ? 'CRITICAL FAIL' : r.result === 'fail' ? 'ISSUES FOUND' : 'PASS'

  const subject = `Pre-Trip Inspection — ${equip} — ${verdict} [${r.id}]`

  const lines: string[] = []
  lines.push('PRE-TRIP INSPECTION')
  lines.push(`Ref: ${r.id}`)
  lines.push(`Equipment: ${equip}${b.equipmentCategory ? ` (${b.equipmentCategory})` : ''}`)
  lines.push(`Inspector: ${r.inspectorName}`)
  lines.push(`Shift: ${r.shift}`)
  if (r.hourMeterReading != null) lines.push(`Hour meter: ${r.hourMeterReading}`)
  lines.push(`Completed: ${fmt(r.createdAt)}`)
  lines.push(`Result: ${verdict}`)
  if (r.workOrderId) lines.push(`Work order created: ${r.workOrderId}`)

  const failed = r.items.filter((i) => i.result === 'fail')
  if (failed.length > 0) {
    lines.push('')
    lines.push('────────────────────')
    lines.push(`FAILED ITEMS (${failed.length})`)
    failed.forEach((i) => {
      lines.push(`  ✗ ${i.label}${i.critical ? ' [safety-critical]' : ''}`)
      if (i.notes) lines.push(`     Note: ${i.notes}`)
    })
  }

  const pass = r.items.filter((i) => i.result === 'pass').length
  const na = r.items.filter((i) => i.result === 'na').length
  lines.push('')
  lines.push('────────────────────')
  lines.push(`Summary: ${pass} pass · ${failed.length} fail · ${na} N/A (${r.items.length} items)`)
  lines.push('')
  lines.push('Generated by Sage EHS')

  return { subject, text: lines.join('\n') }
}

export async function POST(req: Request) {
  const { session, error } = await requireSession()
  if (error) return error

  const rl = await rateLimit(`notify:${session?.user?.email || 'unknown'}`, 10, 60_000)
  if (!rl.ok) {
    return Response.json({ error: 'Too many requests' }, { status: 429, headers: { 'Retry-After': String(rl.retryAfter) } })
  }

  if (!isEmailConfigured()) {
    return Response.json({ emailed: false, reason: 'not-configured' })
  }

  let raw: unknown
  try {
    raw = await req.json()
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const parsed = NotifyBodySchema.safeParse(raw)
  if (!parsed.success) {
    return Response.json({ error: 'Invalid inspection record', details: parsed.error.issues.map((i) => i.message).slice(0, 5) }, { status: 400 })
  }
  const body = parsed.data

  const { subject, text } = buildInspectionEmail(body)
  const outcome = await sendEhsNotification({ subject, text })

  return Response.json({ emailed: outcome === 'sent', outcome })
}
