/**
 * POST /api/inspections/notify
 *
 * Emails a completed pre-trip inspection to the EHS inbox. Best-effort and
 * env-gated: if RESEND_API_KEY is unset this is a no-op (returns emailed:false)
 * so the inspection flow is never blocked. Mirrors the safety review email path.
 */

import { requireSession } from '@/lib/api-auth'
import { rateLimit } from '@/lib/rate-limit'
import { sendEhsNotification, isEmailConfigured, type EhsEmailAttachment } from '@/lib/email-notify'
import { NotifyBodySchema, type NotifyBody } from '@/lib/inspection-notify-schema'
import { reportServerError } from '@/lib/report-error'

function esc(s: unknown): string {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

function fmt(iso: string): string {
  return new Date(iso).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

function buildInspectionEmail(b: NotifyBody, verifiedSubmitter: string | null): { subject: string; text: string } {
  const r = b.record
  const equip = b.equipmentName || `Equipment #${r.equipmentId}`
  const critNaCount = r.criticalNaCount ?? 0
  const naSuffix = critNaCount > 0 ? ` + ${critNaCount} CRITICAL N/A` : ''
  const verdict = r.hasCriticalFail ? 'CRITICAL FAIL' : r.result === 'fail' ? 'ISSUES FOUND' : 'PASS'

  const subject = `Pre-Trip Inspection — ${equip} — ${verdict}${naSuffix} [${r.id}]`

  const lines: string[] = []
  lines.push('PRE-TRIP INSPECTION')
  lines.push(`Ref: ${r.id}`)
  lines.push(`Equipment: ${equip}${b.equipmentCategory ? ` (${b.equipmentCategory})` : ''}`)
  lines.push(`Inspector: ${r.inspectorName}`)
  // Server-stamped from the authenticated session — never client input. Lets
  // EHS distinguish the claimed inspector name from who actually submitted.
  if (verifiedSubmitter) lines.push(`Submitted by (verified): ${verifiedSubmitter}`)
  lines.push(`Shift: ${r.shift}`)
  if (r.hourMeterReading != null) lines.push(`Hour meter: ${r.hourMeterReading}`)
  lines.push(`Completed: ${fmt(r.createdAt)}`)
  lines.push(`Result: ${verdict}`)
  if (r.workOrderId) lines.push(`Work order created: ${r.workOrderId}`)

  const failed = r.items.filter((i) => i.result === 'fail')
  if (failed.length > 0) {
    lines.push('')
    lines.push('────────────────────')
    lines.push(`FAILED ITEMS (${failed.length})`)
    failed.forEach((i) => {
      lines.push(`  ✗ ${i.label}${i.critical ? ' [safety-critical]' : ''}`)
      if (i.notes) lines.push(`     Note: ${i.notes}`)
    })
  }

  const naCritical = r.items.filter((i) => i.critical && i.result === 'na')
  if (naCritical.length > 0) {
    lines.push('')
    lines.push('────────────────────')
    lines.push(`N/A ON SAFETY-CRITICAL ITEMS (${naCritical.length})`)
    naCritical.forEach((i) => {
      const reason = i.naReasonCode || 'no reason provided'
      lines.push(`  ⚠ ${i.label} — ${reason}`)
      if (i.naJustification) lines.push(`     Detail: ${i.naJustification}`)
    })
  }

  const pass = r.items.filter((i) => i.result === 'pass').length
  const na = r.items.filter((i) => i.result === 'na').length
  lines.push('')
  lines.push('────────────────────')
  lines.push(`Summary: ${pass} pass · ${failed.length} fail · ${na} N/A${naCritical.length > 0 ? ` (${naCritical.length} critical)` : ''} (${r.items.length} items)`)
  if (r.hasSignature) lines.push(`Operator sign-on: signed by ${r.inspectorName} (signature PNG attached)`)
  lines.push('')
  lines.push('Generated by Sage EHS')

  return { subject, text: lines.join('\n') }
}

/**
 * Auditable HTML copy: every item with its result, notes, and N/A reasons —
 * not just the exceptions — plus the sign-on block. Table-based with inline
 * styles for email-client compatibility; all user text is escaped.
 */
function buildInspectionEmailHtml(b: NotifyBody, verifiedSubmitter: string | null): string {
  const r = b.record
  const equip = b.equipmentName || `Equipment #${r.equipmentId}`
  const verdict = r.hasCriticalFail ? 'CRITICAL FAIL' : r.result === 'fail' ? 'ISSUES FOUND' : 'PASS'
  const verdictColor = r.hasCriticalFail ? '#B22B2B' : r.result === 'fail' ? '#8A6100' : '#15703D'

  const resultBadge = (item: NotifyBody['record']['items'][number]): string => {
    if (item.result === 'pass') return '<span style="color:#15703D;font-weight:600;">PASS</span>'
    if (item.result === 'fail') return '<span style="color:#B22B2B;font-weight:600;">FAIL</span>'
    return item.critical
      ? '<span style="color:#8A6100;font-weight:600;">N/A ⚠</span>'
      : '<span style="color:#666;">N/A</span>'
  }

  const detailFor = (item: NotifyBody['record']['items'][number]): string => {
    const parts: string[] = []
    if (item.notes) parts.push(esc(item.notes))
    if (item.result === 'na' && item.critical) {
      parts.push(`<em>Reason: ${esc(item.naReasonCode || 'not provided')}</em>`)
      if (item.naJustification) parts.push(esc(item.naJustification))
    }
    return parts.join('<br/>')
  }

  const rows = r.items
    .map(
      (item) => `
      <tr>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:13px;">
          ${esc(item.label)}${item.critical ? ' <span style="background:#FFF4D6;color:#8A6100;font-size:11px;padding:1px 6px;border-radius:8px;">safety-critical</span>' : ''}
        </td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:13px;white-space:nowrap;">${resultBadge(item)}</td>
        <td style="padding:6px 10px;border-bottom:1px solid #eee;font-size:12px;color:#444;">${detailFor(item)}</td>
      </tr>`
    )
    .join('')

  const pass = r.items.filter((i) => i.result === 'pass').length
  const fail = r.items.filter((i) => i.result === 'fail').length
  const na = r.items.filter((i) => i.result === 'na').length
  const naCritical = r.items.filter((i) => i.critical && i.result === 'na').length

  const meta: Array<[string, string]> = [
    ['Reference', esc(r.id)],
    ['Equipment', `${esc(equip)}${b.equipmentCategory ? ` (${esc(b.equipmentCategory)})` : ''}`],
    ['Inspector', esc(r.inspectorName)],
    ...(verifiedSubmitter ? [['Submitted by (verified)', esc(verifiedSubmitter)] as [string, string]] : []),
    ['Shift', esc(r.shift)],
    ...(r.hourMeterReading != null ? [['Hour meter', esc(r.hourMeterReading)] as [string, string]] : []),
    ['Completed', esc(fmt(r.createdAt))],
    ...(r.workOrderId ? [['Work order', esc(r.workOrderId)] as [string, string]] : []),
  ]

  const metaRows = meta
    .map(
      ([k, v]) => `
      <tr>
        <td style="padding:3px 10px 3px 0;font-size:12px;color:#666;white-space:nowrap;">${k}</td>
        <td style="padding:3px 0;font-size:13px;color:#111;">${v}</td>
      </tr>`
    )
    .join('')

  const signatureBlock = r.hasSignature
    ? `<div style="margin-top:20px;padding:14px;border:1px solid #ddd;border-radius:8px;background:#fafafa;">
         <p style="margin:0;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:0.05em;">Operator sign-on</p>
         <p style="margin:6px 0 0;font-size:14px;color:#111;">
           Signed by <strong>${esc(r.inspectorName)}</strong> · ${esc(fmt(r.createdAt))}
         </p>
         <p style="margin:4px 0 0;font-size:12px;color:#666;">
           Touch signature image attached to this email (<code>signature-${esc(r.id)}.png</code>).
         </p>
       </div>`
    : `<p style="margin-top:20px;font-size:12px;color:#8A6100;">No operator signature on record for this inspection.</p>`

  return `
  <div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;max-width:640px;margin:0 auto;padding:24px 16px;color:#111;">
    <p style="margin:0;font-size:12px;color:#666;text-transform:uppercase;letter-spacing:0.08em;">Pre-Trip Inspection — Auditable Copy</p>
    <h1 style="margin:6px 0 2px;font-size:20px;">${esc(equip)}</h1>
    <p style="margin:0 0 16px;font-size:16px;font-weight:700;color:${verdictColor};">${verdict}</p>

    <table cellpadding="0" cellspacing="0" style="margin-bottom:18px;">${metaRows}</table>

    <table cellpadding="0" cellspacing="0" width="100%" style="border:1px solid #eee;border-radius:8px;border-collapse:separate;overflow:hidden;">
      <tr style="background:#f5f5f5;">
        <th align="left" style="padding:8px 10px;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#666;">Item</th>
        <th align="left" style="padding:8px 10px;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#666;">Result</th>
        <th align="left" style="padding:8px 10px;font-size:11px;text-transform:uppercase;letter-spacing:0.05em;color:#666;">Detail</th>
      </tr>
      ${rows}
    </table>

    <p style="margin:14px 0 0;font-size:13px;color:#444;">
      <strong>Summary:</strong> ${pass} pass · ${fail} fail · ${na} N/A${naCritical > 0 ? ` (<span style="color:#8A6100;font-weight:600;">${naCritical} on safety-critical items</span>)` : ''} — ${r.items.length} items
    </p>

    ${signatureBlock}

    <p style="margin-top:24px;font-size:11px;color:#999;">Generated by Sage EHS · Record ${esc(r.id)} · This document reflects the inspection as submitted and is retained on the originating device.</p>
  </div>`
}

export async function POST(req: Request) {
  const { session, error } = await requireSession()
  if (error) return error

  const rl = await rateLimit(`notify:${session?.user?.email || 'unknown'}`, 10, 60_000)
  if (!rl.ok) {
    return Response.json({ error: 'Too many requests' }, { status: 429, headers: { 'Retry-After': String(rl.retryAfter) } })
  }

  if (!isEmailConfigured()) {
    return Response.json({ emailed: false, reason: 'not-configured' })
  }

  let raw: unknown
  try {
    raw = await req.json()
  } catch (err) {
    reportServerError('api/inspections/notify', err)
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const parsed = NotifyBodySchema.safeParse(raw)
  if (!parsed.success) {
    return Response.json({ error: 'Invalid inspection record', details: parsed.error.issues.map((i) => i.message).slice(0, 5) }, { status: 400 })
  }
  const body = parsed.data

  const verifiedSubmitter = session?.user?.email ?? null
  const { subject, text } = buildInspectionEmail(body, verifiedSubmitter)
  const html = buildInspectionEmailHtml(body, verifiedSubmitter)

  // Attach the operator's touch signature as a PNG — the auditable proof of
  // sign-on. The schema already validated it as a PNG data URL.
  const attachments: EhsEmailAttachment[] = []
  if (body.signatureDataUrl) {
    attachments.push({
      filename: `signature-${body.record.id}.png`,
      content: body.signatureDataUrl.split(',')[1],
    })
  }

  const outcome = await sendEhsNotification({ subject, text, html, attachments })

  return Response.json({ emailed: outcome === 'sent', outcome })
}
