/**
 * POST /api/inspections/notify
 *
 * Emails a completed pre-trip inspection to the EHS inbox. Best-effort and
 * env-gated: if RESEND_API_KEY is unset this is a no-op (returns emailed:false)
 * so the inspection flow is never blocked. Mirrors the safety review email path.
 */

import type { InspectionRecord } from '@/lib/types'
import { requireSession } from '@/lib/api-auth'
import { sendEhsNotification, isEmailConfigured } from '@/lib/email-notify'

function fmt(iso: string): string {
  return new Date(iso).toLocaleString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  })
}

interface NotifyBody {
  record: InspectionRecord
  equipmentName?: string
  equipmentCategory?: string
}

function buildInspectionEmail(b: NotifyBody): { subject: string; text: string } {
  const r = b.record
  const equip = b.equipmentName || `Equipment #${r.equipmentId}`
  const verdict = r.hasCriticalFail ? 'CRITICAL FAIL' : r.result === 'fail' ? 'ISSUES FOUND' : 'PASS'

  const subject = `Pre-Trip Inspection — ${equip} — ${verdict} [${r.id}]`

  const lines: string[] = []
  lines.push('PRE-TRIP INSPECTION')
  lines.push(`Ref: ${r.id}`)
  lines.push(`Equipment: ${equip}${b.equipmentCategory ? ` (${b.equipmentCategory})` : ''}`)
  lines.push(`Inspector: ${r.inspectorName}`)
  lines.push(`Shift: ${r.shift}`)
  if (r.hourMeterReading != null) lines.push(`Hour meter: ${r.hourMeterReading}`)
  lines.push(`Completed: ${fmt(r.createdAt)}`)
  lines.push(`Result: ${verdict}`)
  if (r.workOrderId) lines.push(`Work order created: ${r.workOrderId}`)

  const failed = r.items.filter((i) => i.result === 'fail')
  if (failed.length > 0) {
    lines.push('')
    lines.push('────────────────────')
    lines.push(`FAILED ITEMS (${failed.length})`)
    failed.forEach((i) => {
      lines.push(`  ✗ ${i.label}${i.critical ? ' [safety-critical]' : ''}`)
      if (i.notes) lines.push(`     Note: ${i.notes}`)
    })
  }

  const pass = r.items.filter((i) => i.result === 'pass').length
  const na = r.items.filter((i) => i.result === 'na').length
  lines.push('')
  lines.push('────────────────────')
  lines.push(`Summary: ${pass} pass · ${failed.length} fail · ${na} N/A (${r.items.length} items)`)
  lines.push('')
  lines.push('Generated by Sage EHS')

  return { subject, text: lines.join('\n') }
}

export async function POST(req: Request) {
  const { error } = await requireSession()
  if (error) return error

  if (!isEmailConfigured()) {
    return Response.json({ emailed: false, reason: 'not-configured' })
  }

  let body: NotifyBody
  try {
    body = await req.json()
  } catch {
    return Response.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  if (!body?.record?.id || !body.record.items) {
    return Response.json({ error: 'Missing inspection record' }, { status: 400 })
  }

  const { subject, text } = buildInspectionEmail(body)
  const outcome = await sendEhsNotification({ subject, text })

  return Response.json({ emailed: outcome === 'sent', outcome })
}
