#!/usr/bin/env node
// Generate the equipment seed migration from src/data/equipment.ts (KIN-M0-T3).
//
// The repo stays the source of truth for equipment: this script reads the SAME
// array the Vercel app renders from and emits SQL, so the D1 rows can never
// drift from src/data/equipment.ts by hand-transcription. Re-run it whenever
// that file changes and commit the regenerated migration.
//
//   node kin/scripts/gen-seed.mjs           write the migration pair
//   node kin/scripts/gen-seed.mjs --check   regenerate in memory and diff against
//                                           the committed files; exit 1 on drift
//
// SCOPE (deliberate, see docs/roadmap/goals.json log iteration 23): 0002 seeds
// only the pre-trip-REQUIRED units — the 7 that a QR scan can actually open an
// inspection for, which is the whole of the KIN-M0 slice. The equipment TABLE
// carries the complete EquipmentItem column set, so KIN-M1 backfills the other
// 39 rows with a plain INSERT migration and never needs an ALTER.

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO = path.resolve(HERE, '..', '..');
const SOURCE = path.join(REPO, 'src', 'data', 'equipment.ts');
const UP = path.join(REPO, 'kin', 'migrations', '0002_seed_equipment.up.sql');
const DOWN = path.join(REPO, 'kin', 'migrations', '0002_seed_equipment.down.sql');

// Mirrors INSPECTION_CATEGORIES in src/lib/types.ts — the categories for which
// requiresPreTrip() returns true.
const PRE_TRIP_CATEGORIES = ['Powered Industrial Trucks', 'Aerial Work Platforms'];

// camelCase field in EquipmentItem -> snake_case column in the equipment table.
// Explicit rather than derived so a rename on either side fails loudly here.
const COLUMNS = [
  ['itemNumber', 'item_number'],
  ['name', 'name'],
  ['category', 'category'],
  ['oemManual', 'oem_manual'],
  ['manualUrl', 'manual_url'],
  ['manualType', 'manual_type'],
  ['pmDaily', 'pm_daily'],
  ['pmWeekly', 'pm_weekly'],
  ['pmMonthly', 'pm_monthly'],
  ['pmQuarterly', 'pm_quarterly'],
  ['pmSemiAnnual', 'pm_semi_annual'],
  ['pmAnnual', 'pm_annual'],
  ['keyPmSummary', 'key_pm_summary'],
  ['calOshaSections', 'cal_osha_sections'],
  ['calOshaTrainingReq', 'cal_osha_training_req'],
  ['status', 'status'],
  ['location', 'location'],
  ['assetTag', 'asset_tag'],
  ['lastPmDate', 'last_pm_date'],
  ['nextPmDue', 'next_pm_due'],
];

/**
 * Pull the equipmentData array literal out of the TypeScript source and evaluate
 * it. The file imports a type from a '@/' path alias node cannot resolve, so we
 * slice out just the literal — which is plain JS — rather than importing it.
 */
async function loadEquipment() {
  const src = await readFile(SOURCE, 'utf8');
  const marker = src.indexOf('equipmentData');
  if (marker === -1) throw new Error(`equipmentData not found in ${SOURCE}`);
  const start = src.indexOf('[', marker);
  const end = src.lastIndexOf(']');
  if (start === -1 || end === -1 || end < start) {
    throw new Error(`could not locate the equipmentData array literal in ${SOURCE}`);
  }
  const items = new Function(`return ${src.slice(start, end + 1)}`)();
  if (!Array.isArray(items) || items.length === 0) {
    throw new Error('equipmentData parsed to an empty array — refusing to emit an empty seed');
  }
  return items;
}

/** SQL literal for a value: NULL, a number, or a single-quote-escaped string. */
function sqlLiteral(value) {
  if (value === undefined || value === null || value === '') {
    // Empty PM strings are genuinely "no task at this interval", not unknown —
    // but NULL and '' would both render as blank, and NULL keeps the column
    // honest about absence. Empty string is preserved only for required text.
    return value === '' ? "''" : 'NULL';
  }
  if (typeof value === 'number') return String(value);
  if (typeof value === 'boolean') return value ? '1' : '0';
  return `'${String(value).replace(/'/g, "''")}'`;
}

function render(items) {
  const cols = COLUMNS.map(([, col]) => col).join(', ');
  const rows = items.map((item) => {
    const values = COLUMNS.map(([field]) => sqlLiteral(item[field])).join(', ');
    return `INSERT OR REPLACE INTO equipment (${cols})\nVALUES (${values});`;
  });

  const ids = items.map((i) => i.itemNumber).sort((a, b) => a - b);

  const header = (what) =>
    `-- ${what}\n` +
    `-- GENERATED by kin/scripts/gen-seed.mjs from src/data/equipment.ts — DO NOT EDIT BY HAND.\n` +
    `-- Regenerate with: node kin/scripts/gen-seed.mjs\n` +
    `--\n` +
    `-- Seeds the ${items.length} pre-trip-required units (categories: ${PRE_TRIP_CATEGORIES.join(', ')}).\n` +
    `-- These are the only units a QR scan can open an inspection for, which is the\n` +
    `-- whole of the KIN-M0 slice. The equipment table carries the full EquipmentItem\n` +
    `-- column set, so KIN-M1 backfills the remaining units with a plain INSERT.\n`;

  const up =
    header('0002_seed_equipment (up) — equipment rows for the pre-trip slice') +
    `\n${rows.join('\n\n')}\n`;

  // Scoped to exactly the rows this migration inserted, so a down never deletes
  // equipment a later migration added.
  const down =
    header('0002_seed_equipment (down) — remove only the rows 0002 inserted') +
    `\nDELETE FROM equipment WHERE item_number IN (${ids.join(', ')});\n`;

  return { up, down };
}

const all = await loadEquipment();
const seeded = all.filter((item) => PRE_TRIP_CATEGORIES.includes(item.category));
if (seeded.length === 0) {
  throw new Error('no pre-trip-required equipment found — refusing to emit an empty seed');
}
const { up, down } = render(seeded);

if (process.argv.includes('--check')) {
  const [haveUp, haveDown] = await Promise.all([
    readFile(UP, 'utf8').catch(() => null),
    readFile(DOWN, 'utf8').catch(() => null),
  ]);
  const problems = [];
  if (haveUp !== up) problems.push(`${path.relative(REPO, UP)} is out of date`);
  if (haveDown !== down) problems.push(`${path.relative(REPO, DOWN)} is out of date`);
  if (problems.length) {
    console.error('gen-seed --check FAILED:');
    for (const p of problems) console.error(`  - ${p}`);
    console.error('  Run: node kin/scripts/gen-seed.mjs');
    process.exit(1);
  }
  console.log(`gen-seed --check: OK (${seeded.length} seeded units match src/data/equipment.ts)`);
} else {
  await writeFile(UP, up);
  await writeFile(DOWN, down);
  console.log(`gen-seed: wrote ${path.relative(REPO, UP)} and ${path.relative(REPO, DOWN)}`);
  console.log(`  ${seeded.length} of ${all.length} units seeded (pre-trip-required only):`);
  for (const i of seeded) console.log(`    #${i.itemNumber}  ${i.category}  ${i.name.slice(0, 52)}`);
}
