-- ============================================================================
-- 0001_slice.up.sql — KIN-M0-T3: vertical-slice schema for Sage EHS on Kin (D1)
--
-- Creates the four tables the pre-trip inspection slice needs:
--   equipment           full EquipmentItem column set (KIN-M1 needs no ALTER)
--   inspection_records  one row per submitted pre-trip inspection
--   inspection_items    one row per checklist item within a record
--   signatures          R2 object key for the operator signature (never bytes)
--
-- SCHEMA ONLY — no seed data. Equipment rows land separately in
-- 0002_seed_equipment.up.sql, generated by kin/scripts/gen-seed.mjs.
--
-- Conventions (KIN-2, docs/roadmap/goals.json):
--   * snake_case columns mirror the camelCase TS fields in src/lib/types.ts
--   * booleans are INTEGER 0/1; timestamps are TEXT ISO-8601
--   * every record table carries kin_user_id (the x-kin-user-id of the submitter)
--   * inspection_records.sheet_synced_at is the KIN-M4 audit-mirror ledger
--     (docs/kin/NOTIFICATIONS.md) — added now, while the table is empty, so the
--     mirror milestone never has to ALTER a table holding real safety records
-- ============================================================================

-- ---------------------------------------------------------------------------
-- equipment — mirrors EquipmentItem (src/lib/types.ts)
-- Optional TS fields (location?, assetTag?, lastPmDate?, nextPmDue?) are NULL;
-- everything else is NOT NULL (empty string is the TS "blank" value).
-- category is app-guarded (EquipmentCategory union) but intentionally not
-- CHECK-constrained here so a new category never requires a schema migration.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS equipment (
  item_number           INTEGER PRIMARY KEY,
  name                  TEXT    NOT NULL,
  category              TEXT    NOT NULL,
  oem_manual            TEXT    NOT NULL,
  manual_url            TEXT    NOT NULL,
  manual_type           TEXT    NOT NULL
                        CHECK (manual_type IN ('pdf', 'webpage', 'none')),
  pm_daily              TEXT    NOT NULL,
  pm_weekly             TEXT    NOT NULL,
  pm_monthly            TEXT    NOT NULL,
  pm_quarterly          TEXT    NOT NULL,
  pm_semi_annual        TEXT    NOT NULL,
  pm_annual             TEXT    NOT NULL,
  key_pm_summary        TEXT    NOT NULL,
  cal_osha_sections     TEXT    NOT NULL,
  cal_osha_training_req TEXT    NOT NULL,
  status                TEXT    NOT NULL
                        CHECK (status IN ('Active', 'Out of Service', 'Retired', 'Pending Repair')),
  location              TEXT,
  asset_tag             TEXT,
  last_pm_date          TEXT,
  next_pm_due           TEXT
);

-- ---------------------------------------------------------------------------
-- inspection_records — mirrors InspectionRecord (src/lib/types.ts)
-- items[] is normalized into inspection_items; hasSignature stays here as the
-- denormalized flag the TS shape carries, while the R2 key lives in signatures.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inspection_records (
  id                 TEXT    PRIMARY KEY,
  equipment_id       INTEGER NOT NULL REFERENCES equipment(item_number),
  inspector_name     TEXT    NOT NULL,
  shift              TEXT    NOT NULL
                     CHECK (shift IN ('Day', 'Swing', 'Night')),
  hour_meter_reading REAL,
  checklist_type     TEXT    NOT NULL
                     CHECK (checklist_type IN ('electric-forklift', 'scissor-lift', 'walkie-pallet-jack', 'manual-pallet-jack')),
  result             TEXT    NOT NULL
                     CHECK (result IN ('pass', 'fail')),
  has_critical_fail  INTEGER NOT NULL
                     CHECK (has_critical_fail IN (0, 1)),
  critical_na_count  INTEGER NOT NULL,
  work_order_id      TEXT,
  created_at         TEXT    NOT NULL,
  sync_status        TEXT    NOT NULL
                     CHECK (sync_status IN ('pending', 'synced', 'failed', 'offline')),
  notion_page_id     TEXT,
  has_signature      INTEGER
                     CHECK (has_signature IN (0, 1)),
  locale             TEXT
                     CHECK (locale IN ('en', 'es')),
  -- KIN-2: x-kin-user-id of the submitter, on every record table.
  kin_user_id        TEXT    NOT NULL,
  -- KIN-M4 audit-mirror ledger: NULL until the scheduled sweep has appended
  -- this row to the document-controlled Google Sheet (docs/kin/NOTIFICATIONS.md).
  sheet_synced_at    TEXT
);

-- ---------------------------------------------------------------------------
-- inspection_items — mirrors InspectionItemResult (src/lib/types.ts)
-- One row per checklist item. Composite PK (record_id, item_id) enforces one
-- row per item per record AND doubles as the child-lookup index on record_id
-- (leftmost-prefix), so no separate index on record_id is needed.
-- position preserves the checklist's display order.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inspection_items (
  record_id        TEXT    NOT NULL REFERENCES inspection_records(id) ON DELETE CASCADE,
  item_id          TEXT    NOT NULL,
  position         INTEGER NOT NULL,
  label            TEXT    NOT NULL,
  category         TEXT    NOT NULL,
  critical         INTEGER NOT NULL
                   CHECK (critical IN (0, 1)),
  result           TEXT
                   CHECK (result IN ('pass', 'fail', 'na')),
  notes            TEXT    NOT NULL,
  -- R2 object key of the item photo, if any (never inline bytes).
  photo_key        TEXT,
  na_reason_code   TEXT
                   CHECK (na_reason_code IN ('not-installed', 'cannot-access', 'maintenance-in-progress', 'other')),
  na_justification TEXT,
  PRIMARY KEY (record_id, item_id)
);

-- ---------------------------------------------------------------------------
-- signatures — the operator touch signature, stored in R2 (env.STORAGE).
-- Holds the R2 OBJECT KEY only, never base64 bytes. record_id as PRIMARY KEY
-- enforces one signature per inspection and doubles as the FK-child index.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS signatures (
  record_id    TEXT    PRIMARY KEY REFERENCES inspection_records(id) ON DELETE CASCADE,
  storage_key  TEXT    NOT NULL,
  content_type TEXT    NOT NULL,
  byte_size    INTEGER NOT NULL,
  created_at   TEXT    NOT NULL,
  -- KIN-2: x-kin-user-id of the submitter, on every record table.
  kin_user_id  TEXT    NOT NULL
);

-- ---------------------------------------------------------------------------
-- Indexes for the slice's real queries.
-- ---------------------------------------------------------------------------

-- Inspection history per unit (equipment detail page).
CREATE INDEX IF NOT EXISTS idx_inspection_records_equipment_id
  ON inspection_records (equipment_id);

-- "My inspections" per submitter.
CREATE INDEX IF NOT EXISTS idx_inspection_records_kin_user_id
  ON inspection_records (kin_user_id);

-- Recency ordering / date-range listing.
CREATE INDEX IF NOT EXISTS idx_inspection_records_created_at
  ON inspection_records (created_at);

-- KIN-M4 sheet-mirror sweep: SELECT ... WHERE sheet_synced_at IS NULL,
-- consumed oldest-first. Partial index matches that exact predicate and stays
-- near-empty once mirroring keeps up.
CREATE INDEX IF NOT EXISTS idx_inspection_records_sheet_unsynced
  ON inspection_records (created_at)
  WHERE sheet_synced_at IS NULL;
