-- 0002_seed_equipment (down) — remove only the rows 0002 inserted
-- GENERATED by kin/scripts/gen-seed.mjs from src/data/equipment.ts — DO NOT EDIT BY HAND.
-- Regenerate with: node kin/scripts/gen-seed.mjs
--
-- Seeds the 7 pre-trip-required units (categories: Powered Industrial Trucks, Aerial Work Platforms).
-- These are the only units a QR scan can open an inspection for, which is the
-- whole of the KIN-M0 slice. The equipment table carries the full EquipmentItem
-- column set, so KIN-M1 backfills the remaining units with a plain INSERT.

DELETE FROM equipment WHERE item_number IN (21, 22, 23, 24, 25, 26, 27);
